# Generated by Django 5.1.3 on 2026-05-15 12:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('call', 'Call Option'), ('put', 'Put Option')], default='stock', max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=8)),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('executed_at', models.DateTimeField()),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.position')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'is_open'], name='portfolio_p_user_id_cbc2de_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'ticker'], name='portfolio_p_user_id_857692_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active'], name='portfolio_p_user_id_44e1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['position', 'executed_at'], name='portfolio_t_positio_8fd996_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'ticker')},
        ),
    ]
