# Generated by Django 5.1.3 on 2026-05-18 11:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_cost_basis', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_market_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_unrealized_pnl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_unrealized_pnl_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_realized_pnl', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Lifetime cumulative realized P&L through this date.', max_digits=18)),
                ('positions_count', models.IntegerField(default=0)),
                ('prices_captured', models.BooleanField(default=True, help_text='False if at least one position had no cached price.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('asset_type', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cost_basis', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unrealized_pnl_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='portfolio.portfoliosnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', '-date'], name='portfolio_p_user_id_4dee7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='positionsnapshot',
            index=models.Index(fields=['user', 'ticker', '-date'], name='portfolio_p_user_id_ba0970_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='positionsnapshot',
            unique_together={('user', 'date', 'ticker', 'asset_type')},
        ),
    ]
