# Generated by Django 5.1.3 on 2026-05-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=16)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Freeform string tags, e.g. ['earnings', 'breakout']")),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI-generated')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='journal_jou_user_id_1ad335_idx'), models.Index(fields=['user', 'ticker'], name='journal_jou_user_id_62489a_idx')],
            },
        ),
    ]
