# Generated by Django 5.1.3 on 2026-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_jou_user_id_62489a_idx',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='trade_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
