"""
Phase 2 — journal models.

JournalEntry is the user's trade research and notes. Each entry is:
  - Stored in Postgres (source of truth)
  - Mirrored to Elasticsearch via post_save signal (for fast full-text search)

If Elasticsearch is unreachable, the signal logs and continues — Postgres
write always succeeds. Search falls back to Postgres ILIKE in that case.

Why post_save signals instead of a service-layer call:
  - Bulk loading (data migration, fixtures, admin imports) auto-indexes
  - Direct ORM updates (e.g. AI-generated entries) auto-indexes
  - No risk of forgetting to call indexer.update() somewhere
"""

import logging

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver

logger = logging.getLogger(__name__)
    
User = get_user_model()


class JournalEntry(models.Model):
    """A trade journal entry — either written by the user or generated by AI."""

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="journal_entries"
    )
    title = models.CharField(max_length=255)
    body  = models.TextField()

    # Optional ticker link so we can filter by position
    ticker = models.CharField(max_length=16, blank=True, db_index=True)

    # Freeform tags, e.g. ["earnings", "options", "pltr"]
    tags = models.JSONField(default=list)

    # Was this entry generated by the journal-writer AI agent?
    ai_generated = models.BooleanField(default=False)

    # Optional FK to the Trade row that triggered this entry
    trade_id = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes  = [models.Index(fields=["user", "-created_at"])]

    def __str__(self):
        # "[PLTR] Bought PLTR calls" when ticker is set
        # "General thoughts"          when ticker is empty
        ticker_str = f"[{self.ticker}] " if self.ticker else ""
        return f"{ticker_str}{self.title}"


# ─── Elasticsearch auto-sync signals ──────────────────────────
from .documents import JournalEntryDocument

@receiver(post_save, sender=JournalEntry)
def sync_journal_to_es(sender, instance, **kwargs):
    """Index or re-index a journal entry in Elasticsearch after every save."""
    try:
        JournalEntryDocument().update(instance)
    except Exception as exc:
        # ES being down must never block a Postgres write.
        logger.warning("ES sync failed for JournalEntry %s: %s", instance.id, exc)


@receiver(post_delete, sender=JournalEntry)
def remove_journal_from_es(sender, instance, **kwargs):
    """Remove an entry from Elasticsearch when it's deleted from Postgres."""
    try:
        JournalEntryDocument().update(instance, action="delete")
    except Exception as exc:
        logger.warning("ES delete failed for JournalEntry %s: %s", instance.id, exc)
